### ISSUE TITLE
Text/images still cut off on sides

### ISSUE THREAD

**Issue by NikoBoerger** [skydoves/Balloon#52] opened 2020-05-19 08:15 UTC
Hi,

I'm sorry, but for me the latest 1.1.7 Version did not solve the problem. I got the latest version from jcenter, where the "private fun getMeasureTextWidth(measuredWidth: Int): Int" has the parameter already (I double checked in the downloaded dependency).
I am still experiencing the image and text being cut off on my Samsung tablet (see my latest comment in issue #42 ).

Thank you

**Comment by skydoves** [comment] 2020-05-19 08:51
Hi @NikoBoerger 
I just found the issue still occur, and it will be released next version.
But now you can fix it by removing the `setWidthRatio` method.
Thank you for your issue :)

**Comment by NikoBoerger** [comment] 2020-05-19 19:09
Thank you very much for your work!

**Comment by NikoBoerger** [comment] 2020-05-22 08:12
Hi skydoves,

Do you know when you will release the new version? I am planning on releasing my app this weekend and I need the balloon for it. 
If you do not plan on releasing it by then, I will have to manually build your lib (which I am trying to avoid :D ).

Thank you so much!

**Comment by skydoves** [comment] 2020-05-22 17:28
Hi, @NikoBoerger 
The next version will be released in two days.
Thanks :)

**Comment by skydoves** [comment] 2020-05-23 08:58
Hi, @NikoBoerger 
Thank you for your issue :)
Could you please test in your development environment about the issue using a cloned demo project?

**Comment by NikoBoerger** [comment] 2020-05-25 09:53
Of course, I will test it tonight.

**Comment by NikoBoerger** [comment] 2020-05-25 17:16
Hi skydoves, I'm sorry I can't bring better news: I'm still experiencing the exact same issue on the initial broken device. In addition, the image gets cut off on a different device that worked well so far:

![Balloon](https://user-images.githubusercontent.com/8778527/82832671-0f8a8d00-9ebc-11ea-9da3-319065b05d9a.jpg)

**Comment by skydoves** [comment] 2020-05-27 15:52
Hi @NikoBoerger !
It is really hard to represent the issue in my ADB, I tested in 7~10 tablets each different screen size, device environment. If the issue is still happening in the next version, it seems to need more device information and builder options.

![screenshot936675237](https://user-images.githubusercontent.com/24237865/83042808-085ead00-a07d-11ea-99d0-57e2e4a8644e.png)

**Comment by skydoves** [comment] 2020-07-30 11:45
Hi, It is fixed in a new version `1.2.0`!
Thank you for your issue :)

**Comment by skydoves** [comment] 2020-08-14 16:19
#89

**Closed** 2020-09-02 13:41 UTC
Labels: Released
