### ISSUE TITLE
Issues with Nexus 6 Android 7.1.1 device

### ISSUE THREAD

**Issue by cweggler** [skydoves/Balloon#189] opened 2021-05-24 19:17 UTC
- **Library Versions**: 1.3.1 and 1.3.4
- **Affected Device(s)**: Nexus 6, 7.1.1
 
**Describe the Bug:**
On our app when we add the library dependency to our module's gradle:
`implementation "com.github.skydoves:balloon:1.3.1"`

and do nothing else, we notice the issue that transitioning from our Login Activity to another activity, the screen will go black and nothing can be interacted with. Our app does use Android's Jetpack Navigation library to navigate between the two activities. Specifically this version: `2.3.2` so maybe there is some interaction going on there?

When we update to use the 1.3.4 version of this library, we notice the animation in the transition between the two activities stutters and it flips back to the previous activity before going to the next one.

**Expected Behavior:**

This library will not have any interactions with navigation between activities.

**Comment by skydoves** [comment] 2021-05-25 02:22
Him
I'm a little confused because the Jetpack Navigation library navigates between Fragments.
Anyway, navigating those Fragments would be affected by the Balloon.
The Balloon is an independent Window, and it will be attached on a View (If the View is on the Fragment, the Balloon's lifecycle will be followed by the fragment's lifecycle). So I recommend dismissing the balloon before navigating between Fragments.

**Comment by skydoves** [comment] 2021-05-25 16:25
@cweggler 
Thanks for you reporting :)
I think there is a collision of the `fragment-ktx` dependency. The balloon library uses the `fragment-ktx` dependency internally for getting viewLifecycles and fragment's hierarchies, so I recommend removing the ``fragment-ktx` dependency on your gradle file.

```gradle
Implementation("com.github.skydoves:balloon:1.3.4") {
    exclude("androidx.fragment", "fragment-ktx")
  }
```

**Comment by cweggler** [comment] 2021-05-25 22:00
Thank you! We'll give this a try and report back!

**Comment by TatianaArslanova** [comment] 2021-05-26 12:38
I had a similar issue. After adding library 1.3.4 to build.gradle all dialog fragments (androidx.appcompat.app.AppCompatDialogFragment, com.google.android.material.bottomsheet.BottomSheetDialogFragment) started to appear with unexpected transitions. The problem was reproduced on Android Emulator x86 29 API.
I didn't use any baloon methods, just added implementation. It looks like window animation was affected. But the problem is gone after wipe emulator.
I decided to post it when saw this issue)

**Comment by skydoves** [comment] 2021-05-26 12:54
@TatianaArslanova 
In that case, I guess the appcompat dependency has some collision on your project's version. 
Try to the below excluding.

```gradle
Implementation("com.github.skydoves:balloon:1.3.4") {
    exclude(""androidx.appcompat", "appcompat")
  }
```

Thanks!

**Comment by benbackstrom** [comment] 2021-05-26 22:16
It appears that our (me and @cweggler) issue was resolved by excluding `appcompat` as @skydoves pointed to. Thanks for the tip!

**Comment by skydoves** [comment] 2021-05-27 05:36
@benbackstrom 
Thanks for your checking!

**Closed** 2021-05-29 12:14 UTC
