### ISSUE TITLE
Arrow orientation top position not working with custom layout

### ISSUE THREAD

**Issue by MariaGiannaki** [skydoves/Balloon#362] opened 2022-09-06 10:09 UTC
**Please complete the following information:**
- Library Version [v 1.4.7]
- Affected Device(s) All tested devices with Android 11
 
**Describe the Bug:**

setArrowOrientation(ArrowOrientation.TOP) doesn't change the arrow's position to the top of the balloon and the arrow shows at the bottom.
All the other orientations seem to be working as expected.

**Expected Behavior:**

setArrowOrientation(ArrowOrientation.TOP)  should change the arrow's position to the top of the balloon.

**Comment by skydoves** [comment] 2022-09-06 12:10
Hey, could you share your `Balloon.Builder` codes? Also, which method do you use for showing the balloon?

**Comment by skydoves** [comment] 2022-09-06 13:26
Hey, could you build again after removing the `setArrowAlignAnchorPadding` method?

**Comment by MariaGiannaki** [comment] 2022-09-06 14:10
I removed the method but the arrow still shows at the bottom.

**Comment by skydoves** [comment] 2023-05-03 13:02
I'm closing this issue because the issue is outdated.

**Closed by skydoves** 2023-05-03 13:02 UTC
