### ISSUE TITLE
Alignment issues on RTL 

### ISSUE THREAD

**Issue by necatisozer** [skydoves/Balloon#481] opened 2023-08-29 20:30 UTC
**Please complete the following information:**
- Library Version [e.g. v1.5.4]
- Affected Device(s) [all]
 
**Describe the Bug:**

On RTL layouts, balloons are misaligned. Test repo: https://github.com/necatisozer/BalloonTest/

**Comment by 3a4or** [comment] 2023-08-30 07:22
Same issue with me!

**Comment by skydoves** [comment] 2023-08-31 10:44
Hey guys, would you elaborate on this issue? I don't see any RTL options on your test project, such as

```kotlin
CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl)
```

**Comment by necatisozer** [comment] 2023-08-31 11:01
@skydoves Just change phone language to Arabic

**Comment by skydoves** [comment] 2023-08-31 11:22
Alright, I think it seems to Compose issue. It doesn't happen in XML, right?

**Comment by necatisozer** [comment] 2023-08-31 14:02
Yep

**Comment by OlehHaidaienko** [comment] 2023-11-17 12:30
@skydoves Hi, I have the same issue.
Library version: `1.6.2`
Compose BoM: `2023.10.01`
Using the following code you can reproduce the bug. Just switch device language to RTL
```
Box {
    val builder = rememberBalloonBuilder {
        setArrowSize(10)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setPadding(12)
        setCornerRadius(8f)
        setBackgroundColor(Color(0xFF673AB7))
        setBalloonAnimation(BalloonAnimation.ELASTIC)
    }

    Balloon(
        modifier = Modifier.align(Alignment.CenterEnd),
        builder = builder,
        balloonContent = { Text(text = "Now you can edit your profile!", color = Color.White) }
    ) { balloonWindow ->
        Button(
            onClick = {
                balloonWindow.showAlignTop() // display your balloon.
            }
        ) {
            Text(text = "showAlignTop")
        }
    }
}
```
| LTL | RTL |
| --- | --- |
| ![CleanShot 2023-11-17 at 14 14 10](https://github.com/skydoves/Balloon/assets/7819367/209b36a4-99ca-4451-8e23-bbae1c0cd0c1) | ![CleanShot 2023-11-17 at 14 15 50](https://github.com/skydoves/Balloon/assets/7819367/51c3eb9d-6c62-4027-803e-b92c7c68183f) |

I made some investigation and found that the root cause of this issue that `bodyWindow` in compose has width as `WRAP_CONTENT`.  Please try to remove `if` condition in `com.skydoves.balloon.Balloon.Builder:798`. It seems this will fix the bug but I don't know how this will affect library
```
if (!builder.isComposableContent) { // try to remove this check
    this.bodyWindow.width = getMeasuredWidth()
    this.bodyWindow.height = getMeasuredHeight()
}
```

**Comment by skydoves** [comment] 2023-12-27 15:38
Hey @necatisozer @3a4or @OlehHaidaienko, a new version, 1.6.4, has been released, and this issue has been addressed in that version. Please update your library version and reopen this issue if you still need help with the same problem. Thank you for your reporting and patience!

**Closed by skydoves** 2023-12-27 15:38 UTC
Labels: Release Next, compose
